# Generated by Django 5.1.2 on 2024-12-13 11:05

import django.db.models.deletion
import django_ckeditor_5.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True, verbose_name='Tadbir nomi')),
                ('location', models.CharField(max_length=200, null=True, verbose_name='Unversitet')),
                ('build', models.CharField(max_length=200, null=True, verbose_name='Manzil')),
                ('text', models.CharField(max_length=250, null=True, verbose_name='Tadbir mazmuni')),
                ('content', django_ckeditor_5.fields.CKEditor5Field(null=True, verbose_name='Sarlovha umumiy matini')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Tadbir rasmi')),
                ('day', models.DateField(help_text="Tadbir qaysi kunda bo'lishini kiriting", null=True, verbose_name='Kun')),
                ('start_time', models.TimeField(help_text='Tadbir boshlanish vaqtini kiriting (HH:MM:SS)', null=True, verbose_name='Boshlanish vaqti')),
                ('end_time', models.TimeField(help_text='Tadbir tugash vaqtini kiriting (HH:MM:SS)', null=True, verbose_name='Tugash vaqti')),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': "E'lonlar",
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Sarlavha maksimal 200 belgi', max_length=200, null=True, verbose_name='Sarlovhasi')),
                ('text', models.CharField(help_text='Sarlavha matini maksimal 500 belgi', max_length=500, null=True, verbose_name='Sarlovha matini')),
                ('content', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Sarlovha umumiy matini')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Sarlovha rasmi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('share_count', models.IntegerField(default=0)),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Davra suxbatlari',
            },
        ),
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Sarlavha maksimal 200 belgi', max_length=200, null=True, verbose_name='Sarlovhasi')),
                ('text', models.CharField(help_text='Sarlavha matini maksimal 500 belgi', max_length=500, null=True, verbose_name='Sarlovha matini')),
                ('content', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Sarlovha umumiy matini')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Sarlovha rasmi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('share_count', models.IntegerField(default=0)),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Uchrashuvlar',
            },
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Sarlavha maksimal 200 belgi', max_length=200, null=True, verbose_name='Sarlovhasi')),
                ('text', models.CharField(help_text='Sarlavha matini maksimal 500 belgi', max_length=500, null=True, verbose_name='Sarlovha matini')),
                ('slug', models.SlugField(null=True, unique=True)),
                ('content', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Sarlovha umumiy matini')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Sarlovha rasmi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('share_count', models.IntegerField(default=0)),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': "Yig'ilishlar",
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Sarlovha rasmi')),
                ('key', models.CharField(max_length=100, null=True, unique=True)),
                ('title_uz', models.CharField(help_text='Sarlavha maksimal 200 belgi', max_length=200, null=True, verbose_name='Sarlovhasi')),
                ('text_uz', models.CharField(help_text='Sarlavha matini maksimal 500 belgi', max_length=500, null=True, verbose_name='Sarlovha matini')),
                ('content_uz', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Sarlovha umumiy matini')),
                ('title_en', models.CharField(help_text='English sarlavha maksimal 200 belgi', max_length=200, null=True, verbose_name='English sarlovhasi')),
                ('text_en', models.CharField(help_text='English sarlavha matini maksimal 500 belgi', max_length=500, null=True, verbose_name='English sarlovha matini')),
                ('content_en', django_ckeditor_5.fields.CKEditor5Field(null=True, verbose_name='English sarlovha umumiy matini')),
                ('title_ru', models.CharField(help_text='Ruscha sarlavha maksimal 200 belgi', max_length=200, null=True, verbose_name='Ruscha arlovhasi')),
                ('text_ru', models.CharField(help_text='Ruscha sarlavha matini maksimal 500 belgi', max_length=500, null=True, verbose_name='Ruscha arlovha matini')),
                ('content_ru', django_ckeditor_5.fields.CKEditor5Field(null=True, verbose_name='Ruscha sarlovha umumiy matini')),
                ('slug', models.SlugField(null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('share_count', models.IntegerField(default=0)),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Yangiliklar',
            },
        ),
        migrations.CreateModel(
            name='PressConference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Sarlavha maksimal 200 belgi', max_length=200, null=True, verbose_name='Sarlovhasi')),
                ('text', models.CharField(help_text='Sarlavha matini maksimal 500 belgi', max_length=500, null=True, verbose_name='Sarlovha matini')),
                ('content', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Sarlovha umumiy matini')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Sarlovha rasmi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('share_count', models.IntegerField(default=0)),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Matbuot anjumanlar',
            },
        ),
        migrations.CreateModel(
            name='Seminar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Sarlavha maksimal 200 belgi', max_length=200, null=True, verbose_name='Sarlovhasi')),
                ('text', models.CharField(help_text='Sarlavha matini maksimal 500 belgi', max_length=500, null=True, verbose_name='Sarlovha matini')),
                ('content', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Sarlovha umumiy matini')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Sarlovha rasmi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('share_count', models.IntegerField(default=0)),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Seminarlar',
            },
        ),
    ]
