# Generated by Django 5.1.2 on 2024-12-14 04:31

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='announcements',
            old_name='content',
            new_name='content_uz',
        ),
        migrations.RenameField(
            model_name='conversation',
            old_name='text',
            new_name='text_uz',
        ),
        migrations.RenameField(
            model_name='conversation',
            old_name='title',
            new_name='title_uz',
        ),
        migrations.RenameField(
            model_name='designation',
            old_name='text',
            new_name='text_uz',
        ),
        migrations.RenameField(
            model_name='designation',
            old_name='title',
            new_name='title_uz',
        ),
        migrations.RenameField(
            model_name='meeting',
            old_name='text',
            new_name='text_uz',
        ),
        migrations.RenameField(
            model_name='meeting',
            old_name='title',
            new_name='title_uz',
        ),
        migrations.RenameField(
            model_name='pressconference',
            old_name='text',
            new_name='text_uz',
        ),
        migrations.RenameField(
            model_name='pressconference',
            old_name='title',
            new_name='title_uz',
        ),
        migrations.RenameField(
            model_name='seminar',
            old_name='text',
            new_name='text_uz',
        ),
        migrations.RenameField(
            model_name='seminar',
            old_name='title',
            new_name='title_uz',
        ),
        migrations.RemoveField(
            model_name='announcements',
            name='text',
        ),
        migrations.RemoveField(
            model_name='announcements',
            name='title',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='content',
        ),
        migrations.RemoveField(
            model_name='designation',
            name='content',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='content',
        ),
        migrations.RemoveField(
            model_name='pressconference',
            name='content',
        ),
        migrations.RemoveField(
            model_name='seminar',
            name='content',
        ),
        migrations.AddField(
            model_name='announcements',
            name='content_en',
            field=django_ckeditor_5.fields.CKEditor5Field(null=True, verbose_name='English sarlovha umumiy matini'),
        ),
        migrations.AddField(
            model_name='announcements',
            name='content_ru',
            field=django_ckeditor_5.fields.CKEditor5Field(null=True, verbose_name='Ruscha sarlovha umumiy matini'),
        ),
        migrations.AddField(
            model_name='announcements',
            name='text_en',
            field=models.CharField(help_text='English sarlavha matini maksimal 500 belgi', max_length=500, null=True, verbose_name='English sarlovha matini'),
        ),
        migrations.AddField(
            model_name='announcements',
            name='text_ru',
            field=models.CharField(help_text='Ruscha sarlavha matini maksimal 500 belgi', max_length=500, null=True, verbose_name='Ruscha arlovha matini'),
        ),
        migrations.AddField(
            model_name='announcements',
            name='text_uz',
            field=models.CharField(help_text='Sarlavha matini maksimal 500 belgi', max_length=500, null=True, verbose_name='Sarlovha matini'),
        ),
        migrations.AddField(
            model_name='announcements',
            name='title_en',
            field=models.CharField(help_text='English sarlavha maksimal 200 belgi', max_length=200, null=True, verbose_name='English sarlovhasi'),
        ),
        migrations.AddField(
            model_name='announcements',
            name='title_ru',
            field=models.CharField(help_text='Ruscha sarlavha maksimal 200 belgi', max_length=200, null=True, verbose_name='Ruscha arlovhasi'),
        ),
        migrations.AddField(
            model_name='announcements',
            name='title_uz',
            field=models.CharField(help_text='Sarlavha maksimal 200 belgi', max_length=200, null=True, verbose_name='Sarlovhasi'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='content_en',
            field=django_ckeditor_5.fields.CKEditor5Field(null=True, verbose_name='English sarlovha umumiy matini'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='content_ru',
            field=django_ckeditor_5.fields.CKEditor5Field(null=True, verbose_name='Ruscha sarlovha umumiy matini'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='content_uz',
            field=django_ckeditor_5.fields.CKEditor5Field(null=True, verbose_name='Sarlovha umumiy matini'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='text_en',
            field=models.CharField(help_text='English sarlavha matini maksimal 500 belgi', max_length=500, null=True, verbose_name='English sarlovha matini'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='text_ru',
            field=models.CharField(help_text='Ruscha sarlavha matini maksimal 500 belgi', max_length=500, null=True, verbose_name='Ruscha arlovha matini'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='title_en',
            field=models.CharField(help_text='English sarlavha maksimal 200 belgi', max_length=200, null=True, verbose_name='English sarlovhasi'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='title_ru',
            field=models.CharField(help_text='Ruscha sarlavha maksimal 200 belgi', max_length=200, null=True, verbose_name='Ruscha arlovhasi'),
        ),
        migrations.AddField(
            model_name='designation',
            name='content_en',
            field=django_ckeditor_5.fields.CKEditor5Field(null=True, verbose_name='English sarlovha umumiy matini'),
        ),
        migrations.AddField(
            model_name='designation',
            name='content_ru',
            field=django_ckeditor_5.fields.CKEditor5Field(null=True, verbose_name='Ruscha sarlovha umumiy matini'),
        ),
        migrations.AddField(
            model_name='designation',
            name='content_uz',
            field=django_ckeditor_5.fields.CKEditor5Field(null=True, verbose_name='Sarlovha umumiy matini'),
        ),
        migrations.AddField(
            model_name='designation',
            name='text_en',
            field=models.CharField(help_text='English sarlavha matini maksimal 500 belgi', max_length=500, null=True, verbose_name='English sarlovha matini'),
        ),
        migrations.AddField(
            model_name='designation',
            name='text_ru',
            field=models.CharField(help_text='Ruscha sarlavha matini maksimal 500 belgi', max_length=500, null=True, verbose_name='Ruscha arlovha matini'),
        ),
        migrations.AddField(
            model_name='designation',
            name='title_en',
            field=models.CharField(help_text='English sarlavha maksimal 200 belgi', max_length=200, null=True, verbose_name='English sarlovhasi'),
        ),
        migrations.AddField(
            model_name='designation',
            name='title_ru',
            field=models.CharField(help_text='Ruscha sarlavha maksimal 200 belgi', max_length=200, null=True, verbose_name='Ruscha arlovhasi'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='content_en',
            field=django_ckeditor_5.fields.CKEditor5Field(null=True, verbose_name='English sarlovha umumiy matini'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='content_ru',
            field=django_ckeditor_5.fields.CKEditor5Field(null=True, verbose_name='Ruscha sarlovha umumiy matini'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='content_uz',
            field=django_ckeditor_5.fields.CKEditor5Field(null=True, verbose_name='Sarlovha umumiy matini'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='text_en',
            field=models.CharField(help_text='English sarlavha matini maksimal 500 belgi', max_length=500, null=True, verbose_name='English sarlovha matini'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='text_ru',
            field=models.CharField(help_text='Ruscha sarlavha matini maksimal 500 belgi', max_length=500, null=True, verbose_name='Ruscha arlovha matini'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='title_en',
            field=models.CharField(help_text='English sarlavha maksimal 200 belgi', max_length=200, null=True, verbose_name='English sarlovhasi'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='title_ru',
            field=models.CharField(help_text='Ruscha sarlavha maksimal 200 belgi', max_length=200, null=True, verbose_name='Ruscha arlovhasi'),
        ),
        migrations.AddField(
            model_name='pressconference',
            name='content_en',
            field=django_ckeditor_5.fields.CKEditor5Field(null=True, verbose_name='English sarlovha umumiy matini'),
        ),
        migrations.AddField(
            model_name='pressconference',
            name='content_ru',
            field=django_ckeditor_5.fields.CKEditor5Field(null=True, verbose_name='Ruscha sarlovha umumiy matini'),
        ),
        migrations.AddField(
            model_name='pressconference',
            name='content_uz',
            field=django_ckeditor_5.fields.CKEditor5Field(null=True, verbose_name='Sarlovha umumiy matini'),
        ),
        migrations.AddField(
            model_name='pressconference',
            name='text_en',
            field=models.CharField(help_text='English sarlavha matini maksimal 500 belgi', max_length=500, null=True, verbose_name='English sarlovha matini'),
        ),
        migrations.AddField(
            model_name='pressconference',
            name='text_ru',
            field=models.CharField(help_text='Ruscha sarlavha matini maksimal 500 belgi', max_length=500, null=True, verbose_name='Ruscha arlovha matini'),
        ),
        migrations.AddField(
            model_name='pressconference',
            name='title_en',
            field=models.CharField(help_text='English sarlavha maksimal 200 belgi', max_length=200, null=True, verbose_name='English sarlovhasi'),
        ),
        migrations.AddField(
            model_name='pressconference',
            name='title_ru',
            field=models.CharField(help_text='Ruscha sarlavha maksimal 200 belgi', max_length=200, null=True, verbose_name='Ruscha arlovhasi'),
        ),
        migrations.AddField(
            model_name='seminar',
            name='content_en',
            field=django_ckeditor_5.fields.CKEditor5Field(null=True, verbose_name='English sarlovha umumiy matini'),
        ),
        migrations.AddField(
            model_name='seminar',
            name='content_ru',
            field=django_ckeditor_5.fields.CKEditor5Field(null=True, verbose_name='Ruscha sarlovha umumiy matini'),
        ),
        migrations.AddField(
            model_name='seminar',
            name='content_uz',
            field=django_ckeditor_5.fields.CKEditor5Field(null=True, verbose_name='Sarlovha umumiy matini'),
        ),
        migrations.AddField(
            model_name='seminar',
            name='text_en',
            field=models.CharField(help_text='English sarlavha matini maksimal 500 belgi', max_length=500, null=True, verbose_name='English sarlovha matini'),
        ),
        migrations.AddField(
            model_name='seminar',
            name='text_ru',
            field=models.CharField(help_text='Ruscha sarlavha matini maksimal 500 belgi', max_length=500, null=True, verbose_name='Ruscha arlovha matini'),
        ),
        migrations.AddField(
            model_name='seminar',
            name='title_en',
            field=models.CharField(help_text='English sarlavha maksimal 200 belgi', max_length=200, null=True, verbose_name='English sarlovhasi'),
        ),
        migrations.AddField(
            model_name='seminar',
            name='title_ru',
            field=models.CharField(help_text='Ruscha sarlavha maksimal 200 belgi', max_length=200, null=True, verbose_name='Ruscha arlovhasi'),
        ),
    ]
