# Generated by Django 5.1.2 on 2024-12-20 08:50

import django.db.models.deletion
import django_ckeditor_5.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_rename_content_announcements_content_uz_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_uz', models.CharField(help_text='Sarlavha maksimal 200 belgi', max_length=200, null=True, verbose_name='Sarlovhasi')),
                ('content_uz', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Sarlovha umumiy matini')),
                ('title_en', models.CharField(help_text='English sarlavha maksimal 200 belgi', max_length=200, null=True, verbose_name='English sarlovhasi')),
                ('content_en', django_ckeditor_5.fields.CKEditor5Field(null=True, verbose_name='English sarlovha umumiy matini')),
                ('title_ru', models.CharField(help_text='Ruscha sarlavha maksimal 200 belgi', max_length=200, null=True, verbose_name='Ruscha arlovhasi')),
                ('content_ru', django_ckeditor_5.fields.CKEditor5Field(null=True, verbose_name='Ruscha sarlovha umumiy matini')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('share_count', models.IntegerField(default=0)),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': "Bittalik ma'lumotlar",
            },
        ),
    ]
