# Generated by Django 5.1.2 on 2024-12-20 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='post',
            name='key',
        ),
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
    ]
