# Generated by Django 5.1.2 on 2025-01-07 05:39

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_remove_meeting_slug_remove_post_key_remove_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcements',
            name='content_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='English sarlovha umumiy matini'),
        ),
        migrations.AlterField(
            model_name='announcements',
            name='content_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Ruscha sarlovha umumiy matini'),
        ),
        migrations.AlterField(
            model_name='announcements',
            name='content_uz',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Sarlovha umumiy matini'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='content_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='English sarlovha umumiy matini'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='content_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Ruscha sarlovha umumiy matini'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='content_uz',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Sarlovha umumiy matini'),
        ),
        migrations.AlterField(
            model_name='designation',
            name='content_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='English sarlovha umumiy matini'),
        ),
        migrations.AlterField(
            model_name='designation',
            name='content_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Ruscha sarlovha umumiy matini'),
        ),
        migrations.AlterField(
            model_name='designation',
            name='content_uz',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Sarlovha umumiy matini'),
        ),
        migrations.AlterField(
            model_name='details',
            name='content_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='English sarlovha umumiy matini'),
        ),
        migrations.AlterField(
            model_name='details',
            name='content_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Ruscha sarlovha umumiy matini'),
        ),
        migrations.AlterField(
            model_name='details',
            name='content_uz',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Sarlovha umumiy matini'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='content_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='English sarlovha umumiy matini'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='content_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Ruscha sarlovha umumiy matini'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='content_uz',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Sarlovha umumiy matini'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='English sarlovha umumiy matini'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Ruscha sarlovha umumiy matini'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content_uz',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Sarlovha umumiy matini'),
        ),
        migrations.AlterField(
            model_name='pressconference',
            name='content_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='English sarlovha umumiy matini'),
        ),
        migrations.AlterField(
            model_name='pressconference',
            name='content_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Ruscha sarlovha umumiy matini'),
        ),
        migrations.AlterField(
            model_name='pressconference',
            name='content_uz',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Sarlovha umumiy matini'),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='content_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='English sarlovha umumiy matini'),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='content_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Ruscha sarlovha umumiy matini'),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='content_uz',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Sarlovha umumiy matini'),
        ),
    ]
