# Generated by Django 5.1.2 on 2025-02-05 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_alter_announcements_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcements',
            name='build',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Manzil'),
        ),
        migrations.AlterField(
            model_name='announcements',
            name='day',
            field=models.DateField(blank=True, help_text="Tadbir qaysi kunda bo'lishini kiriting", null=True, verbose_name='Kun'),
        ),
        migrations.AlterField(
            model_name='announcements',
            name='end_time',
            field=models.TimeField(blank=True, help_text='Tadbir tugash vaqtini kiriting (HH:MM:SS)', null=True, verbose_name='Tugash vaqti'),
        ),
        migrations.AlterField(
            model_name='announcements',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Unversitet'),
        ),
        migrations.AlterField(
            model_name='announcements',
            name='start_time',
            field=models.TimeField(blank=True, help_text='Tadbir boshlanish vaqtini kiriting (HH:MM:SS)', null=True, verbose_name='Boshlanish vaqti'),
        ),
    ]
