"""
Django settings for samtuit_uz project.

Generated by 'django-admin startproject' using Django 5.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
from django.utils.translation import gettext_lazy as _
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-uzsw2-e58hvo1_#1hu(g_wmth^6*xc8#6e2iz%kra29ig1*3bd'

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = True
DEBUG = False

ALLOWED_HOSTS = ["new.samtuit.uz", "www.new.samtuit.uz", "172.20.20.6", "127.0.0.1", "localhost"]

CSRF_TRUSTED_ORIGINS = ['https://new.samtuit.uz', 'https://www.new.samtuit.uz']

SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')



# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_ckeditor_5',
    'ckeditor',
    'ckeditor_uploader',

    'samtuit',
    'news',
    'leadership',
    'interaktiv',

    'captcha',
]




MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.locale.LocaleMiddleware',  # Ushbu middlewareni qo'shing
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'news.middleware.CaptureIPMiddleware',
    'django.middleware.locale.LocaleMiddleware',
]

LANGUAGE_COOKIE_NAME = 'django_language'
LANGUAGES = [
    ('uz', 'Uzbek'),
    ('ru', 'Russian'),
    ('en', 'English'),
]



ROOT_URLCONF = 'samtuit_uz.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR.joinpath('templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'samtuit_uz.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# DATABASES = {
#    'default': {
#        'ENGINE': 'django.db.backends.sqlite3',
#        'NAME': BASE_DIR / 'db.sqlite3',
#    }
# }

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'samtuit',
        'USER': 'samtuituser',
        'PASSWORD': 'samtuit2025',
        'HOST': 'localhost',
        'PORT': '',
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'uz'
TIME_ZONE = 'Asia/Tashkent'

LANGUAGE_COOKIE_NAME = 'django_language'  # Til cookie'ining nomi
SESSION_ENGINE = 'django.contrib.sessions.backends.db'

USE_I18N = True
USE_L10N = True
USE_TZ = True

LANGUAGES = [
    ('uz', _('O‘zbek')),  # O‘zbek tili
    ('en', _('English')),  # Ingliz tili
    ('ru', _('Русский')),  # Rus tili
]

LOCALE_PATHS = [
    BASE_DIR / 'locale',  # Tarjima fayllarini saqlash uchun joy
]


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/


STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')  # collectstatic uchun

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),  # Statik fayllaringiz joylashgan katalog
]

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media/')


CKEDITOR_UPLOAD_PATH = "uploads/"
CKEDITOR_IMAGE_BACKEND = "pillow"

CKEDITOR_CONFIGS = {
    'extends_uz': {
        'toolbar': 'full',
        'height': 600,
        'width': 1000,
    },
    'extends_en': {
        'toolbar': 'full',
        'height': 600,
        'width': 1000,
    },
    'extends_ru': {
        'toolbar': 'full',
        'height': 600,
        'width': 1000,
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# 30 daqiqa davomida faoliyat bo‘lmasa sessiyani tugatish
SESSION_COOKIE_AGE = 1800  # 30 daqiqa = 1800 soniya

# Sessiya tugashidan so‘ng avtomatik logout
SESSION_EXPIRE_AT_BROWSER_CLOSE = True  # Brauzer yopilganda sessiya tugaydi


HEMIS_OAUTH2_AUTHORIZATION_URL = 'https://student.samtuit.uz/oauth/authorize'
HEMIS_OAUTH2_TOKEN_URL = 'https://student.samtuit.uz/oauth/access-token'
HEMIS_OAUTH2_CLIENT_ID = '4'
HEMIS_OAUTH2_CLIENT_SECRET = 'JlnSenlTkyUzxBWm0RttygUrHOfsi0RZ1hdpUNdZ'
# HEMIS_REDIRECT_URI = 'http://127.0.0.1:8000/callback/'  # Django'da `callback` url
HEMIS_REDIRECT_URI = 'https://new.samtuit.uz/callback/'  # Django'da `callback` url serverda
HEMIS_OATUHT2_API_URL = 'https://student.samtuit.uz/oauth/api/user'

# settings.py
LOGIN_URL = '/login/'
