"""
Django settings for samtuit_uz project.

Generated by 'django-admin startproject' using Django 5.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
from django.utils.translation import gettext_lazy as _
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-uzsw2-e58hvo1_#1hu(g_wmth^6*xc8#6e2iz%kra29ig1*3bd'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ["172.20.20.6", "127.0.0.1", "localhost"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_ckeditor_5',
    'ckeditor',
    'ckeditor_uploader',

    'samtuit',
    'news',
    'leadership'
]




MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.locale.LocaleMiddleware',  # Ushbu middlewareni qo'shing
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'news.middleware.CaptureIPMiddleware',
]

LANGUAGE_COOKIE_NAME = 'django_language'  # Til cookie'ining nomi
SESSION_ENGINE = 'django.contrib.sessions.backends.db'

ROOT_URLCONF = 'samtuit_uz.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR.joinpath('templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'samtuit_uz.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

#DATABASES = {
#    'default': {
#        'ENGINE': 'django.db.backends.sqlite3',
#        'NAME': BASE_DIR / 'db.sqlite3',
#    }
#}

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'samtuit',
        'USER': 'samtuituser',
        'PASSWORD': 'samtuit2025',
        'HOST': 'localhost',
        'PORT': '',
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'uz'
TIME_ZONE = 'Asia/Tashkent'

USE_I18N = True
USE_L10N = True
USE_TZ = True

LANGUAGES = [
    ('uz', _('O‘zbek')),  # O‘zbek tili
    ('en', _('English')),  # Ingliz tili
    ('ru', _('Русский')),  # Rus tili
]

LOCALE_PATHS = [
    BASE_DIR / 'locale',  # Tarjima fayllarini saqlash uchun joy
]


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/


STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')  # collectstatic uchun

#STATICFILES_DIRS = [
#    os.path.join(BASE_DIR, 'static'),  # Statik fayllaringiz joylashgan katalog
#]

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media/')


CKEDITOR_UPLOAD_PATH = "uploads/"
CKEDITOR_IMAGE_BACKEND = "pillow"

CKEDITOR_CONFIGS = {
    'extends_uz': {
        'toolbar': 'full',
        'height': 600,
        'width': 1000,
    },
    'extends_en': {
        'toolbar': 'full',
        'height': 600,
        'width': 1000,
    },
    'extends_ru': {
        'toolbar': 'full',
        'height': 600,
        'width': 1000,
    },
}

# customColorPalette = [
#         {
#             'color': 'hsl(4, 90%, 58%)',
#             'label': 'Red'
#         },
#         {
#             'color': 'hsl(340, 82%, 52%)',
#             'label': 'Pink'
#         },
#         {
#             'color': 'hsl(291, 64%, 42%)',
#             'label': 'Purple'
#         },
#         {
#             'color': 'hsl(262, 52%, 47%)',
#             'label': 'Deep Purple'
#         },
#         {
#             'color': 'hsl(231, 48%, 48%)',
#             'label': 'Indigo'
#         },
#         {
#             'color': 'hsl(207, 90%, 54%)',
#             'label': 'Blue'
#         },
#     ]

# CKEDITOR_5_FILE_STORAGE = "django.core.files.storage.FileSystemStorage"  # Fayllarni saqlash joyi
# CKEDITOR_5_UPLOAD_PATH = "uploads/" 


# CKEDITOR_5_CONFIGS = {
#     'extends_uz': {
#         'toolbar': [
#             'heading', '|', 'outdent', 'indent', '|', 
#             'bold', 'italic', 'link', 'underline', 'strikethrough', 
#             'code', 'subscript', 'superscript', 'highlight', '|',
#             'codeBlock', 'sourceEditing', 'insertImage', 'imageUpload',
#             'bulletedList', 'numberedList', 'todoList', '|', 'blockQuote', 
#             '|', 'fontSize', 'fontFamily', 'fontColor', 'fontBackgroundColor', 
#             'mediaEmbed', 'removeFormat', 'insertTable', 'insertHorizontalRule', 'alignment'
#         ],
#         'image': {
#             'styles': [],
#             'toolbar': [
#                 'imageTextAlternative', '|', 
#                 'imageStyle:alignLeft', 'imageStyle:alignRight', 'imageStyle:alignCenter', 
#                 'imageStyle:side', '|', 'resizeImage:custom', '|'
#             ],
#             'styles': [
#                 'full', 'side', 'alignLeft', 
#                 'alignRight', 'alignCenter',
#             ],
#             'resizeOptions': [
#                 {
#                 'name': 'resizeImage:original',
#                 'label': 'Original'
#                 },
#                 {
#                     'name': 'resizeImage:50',
#                     'value': '50%',
#                     'label': '50%'
#                 },
#                 {
#                     'name': 'resizeImage:75',
#                     'value': '75%',
#                     'label': '75%'
#                 }
#             ]
#         }, 
#         'htmlSupport': {
#             'allow': [
#                 {
#                     'name': 'p',
#                     'attributes': {'style': True},
#                     'classes': True
#                 },
#                 {
#                     'name': 'img',
#                     'attributes': {'src': True, 'width': True, 'height': True, 'alt': True, 'style': True},
#                     'classes': True
#                 }
#             ]
#         },
#         'table': {
#             'contentToolbar': [
#                 'tableColumn', 'tableRow', 'mergeTableCells',
#                 'tableProperties', 'tableCellProperties'
#             ],
#             'tableProperties': {
#                 'borderColors': customColorPalette,
#                 'backgroundColors': customColorPalette
#             },
#             'tableCellProperties': {
#                 'borderColors': customColorPalette,
#                 'backgroundColors': customColorPalette
#             }
#         },
#         'heading': {
#             'options': [
#                 {'model': 'paragraph', 'title': 'Paragraph', 'class': 'ck-heading_paragraph'},
#                 {'model': 'heading1', 'view': 'h1', 'title': 'Heading 1', 'class': 'ck-heading_heading1'},
#                 {'model': 'heading2', 'view': 'h2', 'title': 'Heading 2', 'class': 'ck-heading_heading2'},
#                 {'model': 'heading3', 'view': 'h3', 'title': 'Heading 3', 'class': 'ck-heading_heading3'}
#             ]
#         },
#         'fontSize': {
#             'options': [8, 9, 10, 11, 12, 14, 16, 18, 20, 22, 24, 26, 28, 33, 32, 36, 48]
#         },
#         'alignment': {
#             'options': ['left', 'center', 'right', 'justify']
#         },
#         'upload': {
#             'types': ['png', 'jpg', 'jpeg', 'gif']
#         },
#         'fileTools': {
#             'fileTypes': ['pdf', 'docx', 'pptx'],
#             'uploadUrl': '/upload/',  # Fayllarni yuklash
#         },
#     },
    
#     'extends_en': {
#         'blockToolbar': [
#             'paragraph', 'heading1', 'heading2', 'heading3', 
#             '|', 'bulletedList', 'numberedList', 
#             '|', 'blockQuote',
#         ],
#         'language': 'en',
#         'toolbar': [
#             'heading', '|', 'outdent', 'indent', '|', 
#             'bold', 'italic', 'link', 'underline', 'strikethrough',
#             'code', 'subscript', 'superscript', 'highlight', '|', 
#             'codeBlock', 'sourceEditing', 'insertImage',
#             'bulletedList', 'numberedList', 'todoList', '|', 
#             'blockQuote', 'imageUpload', '|',
#             'fontSize', 'fontFamily', 'fontColor', 
#             'fontBackgroundColor', 'mediaEmbed', 
#             'removeFormat', 'insertTable', 'insertHorizontalRule',
#             'alignment'  # Alignment qo'shildi
#         ],
#         'image': {
#             'toolbar': [
#                 'imageTextAlternative', '|', 'imageStyle:alignLeft',
#                 'imageStyle:alignRight', 'imageStyle:alignCenter', 
#                 'imageStyle:side', '|'
#             ],
#             'styles': [
#                 'full', 'side', 'alignLeft', 
#                 'alignRight', 'alignCenter',
#             ]
#         },
#         'table': {
#             'contentToolbar': [
#                 'tableColumn', 'tableRow', 'mergeTableCells',
#                 'tableProperties', 'tableCellProperties'
#             ],
#             'tableProperties': {
#                 'borderColors': customColorPalette,
#                 'backgroundColors': customColorPalette
#             },
#             'tableCellProperties': {
#                 'borderColors': customColorPalette,
#                 'backgroundColors': customColorPalette
#             }
#         },
#         'heading': {
#             'options': [
#                 {'model': 'paragraph', 'title': 'Paragraph', 'class': 'ck-heading_paragraph'},
#                 {'model': 'heading1', 'view': 'h1', 'title': 'Heading 1', 'class': 'ck-heading_heading1'},
#                 {'model': 'heading2', 'view': 'h2', 'title': 'Heading 2', 'class': 'ck-heading_heading2'},
#                 {'model': 'heading3', 'view': 'h3', 'title': 'Heading 3', 'class': 'ck-heading_heading3'}
#             ]
#         },
#         'upload': {
#             'types': ['png', 'jpg', 'jpeg', 'gif']
#         }
#     },
    
#     'extends_ru': {
#         'blockToolbar': [
#             'paragraph', 'heading1', 'heading2', 'heading3', 
#             '|', 'bulletedList', 'numberedList', 
#             '|', 'blockQuote',
#         ],
#         'language': 'ru',
#         'toolbar': [
#             'heading', '|', 'outdent', 'indent', '|', 
#             'bold', 'italic', 'link', 'underline', 'strikethrough',
#             'code', 'subscript', 'superscript', 'highlight', '|', 
#             'codeBlock', 'sourceEditing', 'insertImage',
#             'bulletedList', 'numberedList', 'todoList', '|', 
#             'blockQuote', 'imageUpload', '|',
#             'fontSize', 'fontFamily', 'fontColor', 
#             'fontBackgroundColor', 'mediaEmbed', 
#             'removeFormat', 'insertTable', 'insertHorizontalRule',
#             'alignment'  # Alignment qo'shildi
#         ],
#         'image': {
#             'toolbar': [
#                 'imageTextAlternative', '|', 'imageStyle:alignLeft',
#                 'imageStyle:alignRight', 'imageStyle:alignCenter', 
#                 'imageStyle:side', '|'
#             ],
#             'styles': [
#                 'full', 'side', 'alignLeft', 
#                 'alignRight', 'alignCenter',
#             ]
#         },
#         'table': {
#             'contentToolbar': [
#                 'tableColumn', 'tableRow', 'mergeTableCells',
#                 'tableProperties', 'tableCellProperties'
#             ],
#             'tableProperties': {
#                 'borderColors': customColorPalette,
#                 'backgroundColors': customColorPalette
#             },
#             'tableCellProperties': {
#                 'borderColors': customColorPalette,
#                 'backgroundColors': customColorPalette
#             }
#         },
#         'heading': {
#             'options': [
#                 {'model': 'paragraph', 'title': 'Paragraph', 'class': 'ck-heading_paragraph'},
#                 {'model': 'heading1', 'view': 'h1', 'title': 'Heading 1', 'class': 'ck-heading_heading1'},
#                 {'model': 'heading2', 'view': 'h2', 'title': 'Heading 2', 'class': 'ck-heading_heading2'},
#                 {'model': 'heading3', 'view': 'h3', 'title': 'Heading 3', 'class': 'ck-heading_heading3'}
#             ]
#         },
#         'upload': {
#             'types': ['png', 'jpg', 'jpeg', 'gif']
#         }
#     },
    
#     'list': {
#         'properties': {
#             'styles': 'true',
#             'startIndex': 'true',
#             'reversed': 'true',
#         }
#     }
# }


# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
