# Generated by Django 5.1.2 on 2024-12-13 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True, verbose_name='Hamkor nomi')),
                ('link', models.CharField(blank=True, max_length=500, null=True, verbose_name='Hamkor web sayt linki')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Hamkor rasmi .png')),
            ],
            options={
                'verbose_name_plural': 'Hamkorlar',
            },
        ),
        migrations.CreateModel(
            name='PictureSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Silayder rasmlari yuklash uchun', upload_to='silder/')),
            ],
            options={
                'verbose_name_plural': 'Rasm Slayderlari',
            },
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frist_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('student_image', models.ImageField(blank=True, null=True, upload_to='student_images/')),
                ('candidate', models.CharField(blank=True, max_length=250, null=True)),
                ('descriptions', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Talabalar',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_uz', models.CharField(max_length=255, verbose_name='Uzbek tilida sarlavha')),
                ('title_ru', models.CharField(max_length=255, verbose_name='Rus tilida sarlavha')),
                ('title_en', models.CharField(max_length=255, verbose_name='Ingliz tilida sarlavha')),
                ('url', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='samtuit.menu')),
            ],
            options={
                'verbose_name': 'Menu',
            },
        ),
    ]
