# Generated by Django 5.1.2 on 2024-12-14 06:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samtuit', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Celebrities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, help_text='Rasm o‘lchami 100x100 piksel bo‘lishi kerak!', null=True, upload_to='images/', verbose_name='Muallif rasmi')),
                ('title_uz', models.CharField(blank=True, help_text="O'zbek tilida yozing. Maksimal 250 belgi", max_length=250, null=True, verbose_name='Muallif ismi')),
                ('text_uz', models.CharField(blank=True, help_text="O'zbek tilida yozing. Maksimal 500 belgi", max_length=600, null=True, verbose_name="Muallif so'zi")),
                ('title_en', models.CharField(blank=True, help_text='Engliz tilida yozing. Maksimal 250 belgi', max_length=250, null=True, verbose_name='Muallif ismi')),
                ('text_en', models.CharField(blank=True, help_text='Engliz tilida yozing. Maksimal 500 belgi', max_length=600, null=True, verbose_name="Muallif so'zi")),
                ('title_ru', models.CharField(blank=True, help_text='Rus tilida yozing. Maksimal 250 belgi', max_length=250, null=True, verbose_name='Muallif ismi')),
                ('text_ru', models.CharField(blank=True, help_text='Rus tilida yozing. Maksimal 500 belgi', max_length=600, null=True, verbose_name="Muallif so'zi")),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Wisdom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_uz', models.CharField(blank=True, help_text="O'zbek tilida yozing. Maksimal 250 belgi", max_length=250, null=True, verbose_name='Muallif ismi')),
                ('text_uz', models.CharField(blank=True, help_text="O'zbek tilida yozing. Maksimal 500 belgi", max_length=600, null=True, verbose_name="Muallif so'zi")),
                ('title_en', models.CharField(blank=True, help_text='Engliz tilida yozing. Maksimal 250 belgi', max_length=250, null=True, verbose_name='Muallif ismi')),
                ('text_en', models.CharField(blank=True, help_text='Engliz tilida yozing. Maksimal 500 belgi', max_length=600, null=True, verbose_name="Muallif so'zi")),
                ('title_ru', models.CharField(blank=True, help_text='Rus tilida yozing. Maksimal 250 belgi', max_length=250, null=True, verbose_name='Muallif ismi')),
                ('text_ru', models.CharField(blank=True, help_text='Rus tilida yozing. Maksimal 500 belgi', max_length=600, null=True, verbose_name="Muallif so'zi")),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Kun hikmatlari',
            },
        ),
    ]
