# Generated by Django 4.2.17 on 2024-12-18 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samtuit', '0003_alter_celebrities_options_alter_menu_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='linked_model',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Bog'liq model"),
        ),
        migrations.AddField(
            model_name='menu',
            name='linked_object',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="Bog'liq obyekt ID"),
        ),
        migrations.AddField(
            model_name='menu',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Tartib'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='menu_type',
            field=models.CharField(choices=[('list', 'List'), ('detail', 'Detail')], max_length=10, verbose_name='Menyu turi'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='title_en',
            field=models.CharField(max_length=100, verbose_name='Ingliz tilida menu'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='title_ru',
            field=models.CharField(max_length=100, verbose_name='Rus tilida menu'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='title_uz',
            field=models.CharField(max_length=100, verbose_name='Uzbek tilida menu'),
        ),
        migrations.DeleteModel(
            name='MenuItem',
        ),
    ]
