# Generated by Django 5.1.2 on 2024-12-20 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samtuit', '0005_alter_menu_options_menu_parent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ['parent__id'], 'verbose_name': 'Menyu', 'verbose_name_plural': 'Menyular'},
        ),
        migrations.RemoveField(
            model_name='menu',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='linked_model',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='linked_object',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='menu_type',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='order',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='slug',
        ),
        migrations.AddField(
            model_name='menu',
            name='url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
