# Generated by Django 5.1.2 on 2024-12-20 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samtuit', '0006_alter_menu_options_remove_menu_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(default='Fasllar', max_length=50)),
                ('snow', models.BooleanField()),
                ('leaf', models.BooleanField()),
                ('rain', models.BooleanField()),
                ('spring', models.BooleanField()),
            ],
        ),
    ]
