# Generated by Django 5.1.2 on 2024-12-20 10:31

import django.db.models.deletion
import django_ckeditor_5.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samtuit', '0007_season'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ListsMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_uz', models.CharField(max_length=100, verbose_name='Uzbek tilida menu')),
                ('title_en', models.CharField(max_length=100, verbose_name='Engliz tilida menu')),
                ('title_ru', models.CharField(max_length=100, verbose_name='Rus tilida menu')),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'verbose_name': 'Menyular',
            },
        ),
        migrations.AlterModelOptions(
            name='menu',
            options={'verbose_name': 'Menyu', 'verbose_name_plural': 'Menyular'},
        ),
        migrations.CreateModel(
            name='Lists',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Sarlovha rasmi')),
                ('title_uz', models.CharField(help_text='Sarlavha maksimal 200 belgi', max_length=200, null=True, verbose_name='Sarlovhasi')),
                ('text_uz', models.CharField(help_text='Sarlavha matini maksimal 500 belgi', max_length=500, null=True, verbose_name='Sarlovha matini')),
                ('content_uz', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Sarlovha umumiy matini')),
                ('title_en', models.CharField(help_text='English sarlavha maksimal 200 belgi', max_length=200, null=True, verbose_name='English sarlovhasi')),
                ('text_en', models.CharField(help_text='English sarlavha matini maksimal 500 belgi', max_length=500, null=True, verbose_name='English sarlovha matini')),
                ('content_en', django_ckeditor_5.fields.CKEditor5Field(null=True, verbose_name='English sarlovha umumiy matini')),
                ('title_ru', models.CharField(help_text='Ruscha sarlavha maksimal 200 belgi', max_length=200, null=True, verbose_name='Ruscha arlovhasi')),
                ('text_ru', models.CharField(help_text='Ruscha sarlavha matini maksimal 500 belgi', max_length=500, null=True, verbose_name='Ruscha arlovha matini')),
                ('content_ru', django_ckeditor_5.fields.CKEditor5Field(null=True, verbose_name='Ruscha sarlovha umumiy matini')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('share_count', models.IntegerField(default=0)),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('listmenu', models.ForeignKey(blank=True, help_text='Menuyuda aks etadi', null=True, on_delete=django.db.models.deletion.SET_NULL, to='samtuit.listsmenu', verbose_name='Menusi')),
            ],
            options={
                'verbose_name_plural': "Qoshimcha ma'lumotlar",
            },
        ),
    ]
