# Generated by Django 5.1.2 on 2024-12-21 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samtuit', '0008_listsmenu_alter_menu_options_lists'),
    ]

    operations = [
        migrations.AddField(
            model_name='lists',
            name='url',
            field=models.CharField(blank=True, help_text='Boshqa web saytga yonaltirish', max_length=255, null=True, verbose_name='Url'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='url',
            field=models.CharField(blank=True, default='http://127.0.0.1:8000/views/', max_length=200, null=True),
        ),
    ]
