# Generated by Django 5.1.1 on 2024-09-27 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samtuit', '0008_post_share_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='PictureSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='silder/')),
            ],
        ),
    ]
