# Generated by Django 5.1.2 on 2024-12-23 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samtuit', '0009_lists_url_alter_menu_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lists',
            name='image',
        ),
        migrations.AlterField(
            model_name='listsmenu',
            name='slug',
            field=models.SlugField(blank=True, help_text='Ushbu urlni tanlangan Menu saxifasidagi urlga joylashtiring', unique=True, verbose_name='Url'),
        ),
    ]
