# Generated by Django 5.1.2 on 2024-12-10 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samtuit', '0010_students'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('location', models.CharField(max_length=200, null=True)),
                ('build', models.CharField(max_length=200, null=True)),
                ('text', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
            options={
                'verbose_name_plural': "E'lonlar",
            },
        ),
        migrations.AlterModelOptions(
            name='pictureslider',
            options={'verbose_name_plural': 'Rasm Slayderlari'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name_plural': 'Yangiliklar'},
        ),
        migrations.AlterModelOptions(
            name='students',
            options={'verbose_name_plural': 'Talabalar'},
        ),
    ]
