# Generated by Django 5.1.2 on 2024-12-24 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samtuit', '0011_listsmenu_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='lists',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to='files'),
        ),
    ]
