# Generated by Django 5.1.2 on 2024-12-10 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samtuit', '0011_announcements_alter_pictureslider_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcements',
            name='day',
            field=models.DateField(help_text="Tadbir qaysi kunda bo'lishini kiriting", null=True, verbose_name='Kun'),
        ),
        migrations.AddField(
            model_name='announcements',
            name='end_time',
            field=models.TimeField(help_text='Tadbir tugash vaqtini kiriting (HH:MM:SS)', null=True, verbose_name='Tugash vaqti'),
        ),
        migrations.AddField(
            model_name='announcements',
            name='start_time',
            field=models.TimeField(help_text='Tadbir boshlanish vaqtini kiriting (HH:MM:SS)', null=True, verbose_name='Boshlanish vaqti'),
        ),
        migrations.AlterField(
            model_name='announcements',
            name='title',
            field=models.CharField(max_length=200, null=True, verbose_name='Tadbir nomi'),
        ),
    ]
