# Generated by Django 5.1.2 on 2024-12-12 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samtuit', '0012_announcements_day_announcements_end_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True, verbose_name='Hamkor nomi')),
                ('link', models.CharField(blank=True, max_length=500, null=True, verbose_name='Hamkor web sayt linki')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Hamkor rasmi .png')),
            ],
            options={
                'verbose_name_plural': 'Hamkorlar',
            },
        ),
        migrations.AlterField(
            model_name='announcements',
            name='build',
            field=models.CharField(max_length=200, null=True, verbose_name='Manzil'),
        ),
        migrations.AlterField(
            model_name='announcements',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Tadbir rasmi'),
        ),
        migrations.AlterField(
            model_name='announcements',
            name='location',
            field=models.CharField(max_length=200, null=True, verbose_name='Unversitet'),
        ),
        migrations.AlterField(
            model_name='announcements',
            name='text',
            field=models.TextField(null=True, verbose_name='Tadbir mazmuni'),
        ),
    ]
