# Generated by Django 5.1.2 on 2024-12-24 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samtuit', '0012_lists_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='listsmenu',
            name='url',
            field=models.CharField(blank=True, default='http://127.0.0.1:8000/views/<django.db.models.fields.SlugField>/', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='lists',
            name='files',
            field=models.FileField(blank=True, help_text="Fayl yuklash agar kerak bo'lsa", null=True, upload_to='files', verbose_name='Fayl'),
        ),
        migrations.AlterField(
            model_name='listsmenu',
            name='slug',
            field=models.SlugField(blank=True, help_text='Ushbu urlni tanlangan Menu saxifasidagi urlga joylashtiring', unique=True, verbose_name='Slug'),
        ),
    ]
