# Generated by Django 5.1.2 on 2024-12-12 09:40

import django.db.models.deletion
import django_ckeditor_5.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samtuit', '0013_partners_alter_announcements_build_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='announcements',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(null=True, verbose_name='Sarlovha umumiy matini'),
        ),
        migrations.AddField(
            model_name='announcements',
            name='created_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='announcements',
            name='text',
            field=models.CharField(max_length=250, null=True, verbose_name='Tadbir mazmuni'),
        ),
        migrations.AlterField(
            model_name='pictureslider',
            name='image',
            field=models.ImageField(help_text='Silayder rasmlari yuklash uchun', upload_to='silder/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Sarlovha umumiy matini'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Sarlovha rasmi'),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.CharField(help_text='Sarlavha matini maksimal 500 belgi', max_length=500, null=True, verbose_name='Sarlovha matini'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(help_text='Sarlavha maksimal 200 belgi', max_length=200, null=True, verbose_name='Sarlovhasi'),
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Sarlavha maksimal 200 belgi', max_length=200, null=True, verbose_name='Sarlovhasi')),
                ('text', models.CharField(help_text='Sarlavha matini maksimal 500 belgi', max_length=500, null=True, verbose_name='Sarlovha matini')),
                ('content', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Sarlovha umumiy matini')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Sarlovha rasmi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('share_count', models.IntegerField(default=0)),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Davra suxbatlari',
            },
        ),
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Sarlavha maksimal 200 belgi', max_length=200, null=True, verbose_name='Sarlovhasi')),
                ('text', models.CharField(help_text='Sarlavha matini maksimal 500 belgi', max_length=500, null=True, verbose_name='Sarlovha matini')),
                ('content', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Sarlovha umumiy matini')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Sarlovha rasmi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('share_count', models.IntegerField(default=0)),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Uchrashuvlar',
            },
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Sarlavha maksimal 200 belgi', max_length=200, null=True, verbose_name='Sarlovhasi')),
                ('text', models.CharField(help_text='Sarlavha matini maksimal 500 belgi', max_length=500, null=True, verbose_name='Sarlovha matini')),
                ('content', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Sarlovha umumiy matini')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Sarlovha rasmi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('share_count', models.IntegerField(default=0)),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': "Yig'ilishlar",
            },
        ),
        migrations.CreateModel(
            name='PressConference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Sarlavha maksimal 200 belgi', max_length=200, null=True, verbose_name='Sarlovhasi')),
                ('text', models.CharField(help_text='Sarlavha matini maksimal 500 belgi', max_length=500, null=True, verbose_name='Sarlovha matini')),
                ('content', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Sarlovha umumiy matini')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Sarlovha rasmi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('share_count', models.IntegerField(default=0)),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Matbuot anjumanlar',
            },
        ),
        migrations.CreateModel(
            name='Seminar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Sarlavha maksimal 200 belgi', max_length=200, null=True, verbose_name='Sarlovhasi')),
                ('text', models.CharField(help_text='Sarlavha matini maksimal 500 belgi', max_length=500, null=True, verbose_name='Sarlovha matini')),
                ('content', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Sarlovha umumiy matini')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Sarlovha rasmi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('share_count', models.IntegerField(default=0)),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Seminarlar',
            },
        ),
    ]
