# Generated by Django 5.1.2 on 2024-12-24 06:52

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samtuit', '0013_listsmenu_url_alter_lists_files_alter_listsmenu_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostOne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.AlterField(
            model_name='lists',
            name='text_en',
            field=models.CharField(blank=True, help_text='English sarlavha matini maksimal 500 belgi', max_length=500, null=True, verbose_name='English sarlovha matini'),
        ),
        migrations.AlterField(
            model_name='lists',
            name='text_ru',
            field=models.CharField(blank=True, help_text='Ruscha sarlavha matini maksimal 500 belgi', max_length=500, null=True, verbose_name='Ruscha arlovha matini'),
        ),
        migrations.AlterField(
            model_name='lists',
            name='text_uz',
            field=models.CharField(blank=True, help_text='Sarlavha matini maksimal 500 belgi', max_length=500, null=True, verbose_name='Sarlovha matini'),
        ),
        migrations.AlterField(
            model_name='listsmenu',
            name='url',
            field=models.CharField(blank=True, default='http://127.0.0.1:8000/views/', max_length=200, null=True),
        ),
    ]
