# Generated by Django 5.1.2 on 2024-12-12 10:21

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samtuit', '0014_announcements_content_announcements_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content_en',
            field=django_ckeditor_5.fields.CKEditor5Field(null=True, verbose_name='English sarlovha umumiy matini'),
        ),
        migrations.AddField(
            model_name='post',
            name='content_ru',
            field=django_ckeditor_5.fields.CKEditor5Field(null=True, verbose_name='Ruscha sarlovha umumiy matini'),
        ),
        migrations.AddField(
            model_name='post',
            name='key',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='post',
            name='text_en',
            field=models.CharField(help_text='English sarlavha matini maksimal 500 belgi', max_length=500, null=True, verbose_name='Sarlovha matini'),
        ),
        migrations.AddField(
            model_name='post',
            name='text_ru',
            field=models.CharField(help_text='Ruscha sarlavha matini maksimal 500 belgi', max_length=500, null=True, verbose_name='Sarlovha matini'),
        ),
        migrations.AddField(
            model_name='post',
            name='title_en',
            field=models.CharField(help_text='English sarlavha maksimal 200 belgi', max_length=200, null=True, verbose_name='Sarlovhasi'),
        ),
        migrations.AddField(
            model_name='post',
            name='title_ru',
            field=models.CharField(help_text='Ruscha sarlavha maksimal 200 belgi', max_length=200, null=True, verbose_name='Sarlovhasi'),
        ),
    ]
