# Generated by Django 5.1.2 on 2024-12-12 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samtuit', '0015_post_content_en_post_content_ru_post_key_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='content_uz',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='text',
            new_name='text_uz',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='title_uz',
        ),
        migrations.AlterField(
            model_name='post',
            name='text_en',
            field=models.CharField(help_text='English sarlavha matini maksimal 500 belgi', max_length=500, null=True, verbose_name='English sarlovha matini'),
        ),
        migrations.AlterField(
            model_name='post',
            name='text_ru',
            field=models.CharField(help_text='Ruscha sarlavha matini maksimal 500 belgi', max_length=500, null=True, verbose_name='Ruscha arlovha matini'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title_en',
            field=models.CharField(help_text='English sarlavha maksimal 200 belgi', max_length=200, null=True, verbose_name='English sarlovhasi'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title_ru',
            field=models.CharField(help_text='Ruscha sarlavha maksimal 200 belgi', max_length=200, null=True, verbose_name='Ruscha arlovhasi'),
        ),
    ]
