# Generated by Django 5.1.2 on 2024-12-24 07:10

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('samtuit', '0015_postone_content2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postone',
            name='content',
        ),
        migrations.AlterField(
            model_name='postone',
            name='content2',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
