# Generated by Django 5.1.2 on 2024-12-24 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('samtuit', '0016_remove_postone_content_alter_postone_content2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostOne',
        ),
    ]
