# Generated by Django 5.1.2 on 2025-01-07 05:39

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('samtuit', '0017_delete_postone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lists',
            name='content_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='English sarlovha umumiy matini'),
        ),
        migrations.AlterField(
            model_name='lists',
            name='content_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Ruscha sarlovha umumiy matini'),
        ),
        migrations.AlterField(
            model_name='lists',
            name='content_uz',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Sarlovha umumiy matini'),
        ),
    ]
