# Generated by Django 5.1.2 on 2025-01-07 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('samtuit', '0018_alter_lists_content_en_alter_lists_content_ru_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Celebrities',
        ),
    ]
