# Generated by Django 5.1.2 on 2025-01-07 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samtuit', '0019_delete_celebrities'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wisdom',
            options={'verbose_name_plural': 'Savollar va javoblar'},
        ),
        migrations.AlterField(
            model_name='wisdom',
            name='text_en',
            field=models.CharField(blank=True, help_text='Engliz tilida yozing. Maksimal 600 belgi', max_length=600, null=True, verbose_name='Javoblar'),
        ),
        migrations.AlterField(
            model_name='wisdom',
            name='text_ru',
            field=models.CharField(blank=True, help_text='Rus tilida yozing. Maksimal 600 belgi', max_length=600, null=True, verbose_name='Javoblar'),
        ),
        migrations.AlterField(
            model_name='wisdom',
            name='text_uz',
            field=models.CharField(blank=True, help_text="O'zbek tilida yozing. Maksimal 600 belgi", max_length=600, null=True, verbose_name='Javoblar'),
        ),
        migrations.AlterField(
            model_name='wisdom',
            name='title_en',
            field=models.CharField(blank=True, help_text='Engliz tilida yozing. Maksimal 250 belgi', max_length=250, null=True, verbose_name='Savollar'),
        ),
        migrations.AlterField(
            model_name='wisdom',
            name='title_ru',
            field=models.CharField(blank=True, help_text='Rus tilida yozing. Maksimal 250 belgi', max_length=250, null=True, verbose_name='Savollar'),
        ),
        migrations.AlterField(
            model_name='wisdom',
            name='title_uz',
            field=models.CharField(blank=True, help_text="O'zbek tilida yozing. Maksimal 250 belgi", max_length=250, null=True, verbose_name='Savollar'),
        ),
    ]
