# Generated by Django 5.1.2 on 2025-01-08 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samtuit', '0021_listsmenu_created_at_listsmenu_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lists',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='listsmenu',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='partners',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='pictureslider',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='season',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='wisdom',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
