# Generated by Django 5.1.2 on 2025-01-08 08:05

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('samtuit', '0022_alter_lists_created_at_alter_listsmenu_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lists',
            name='content_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='English sarlovha umumiy matini'),
        ),
        migrations.AlterField(
            model_name='lists',
            name='content_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Ruscha sarlovha umumiy matini'),
        ),
        migrations.AlterField(
            model_name='lists',
            name='content_uz',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Sarlovha umumiy matini'),
        ),
    ]
