# Generated by Django 5.1.2 on 2025-01-08 13:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samtuit', '0023_alter_lists_content_en_alter_lists_content_ru_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuickMmenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_uz', models.CharField(max_length=100, verbose_name='Uzbek tilida menu')),
                ('title_ru', models.CharField(max_length=100, verbose_name='Rus tilida menu')),
                ('title_en', models.CharField(max_length=100, verbose_name='Ingliz tilida menu')),
                ('url', models.CharField(blank=True, default='http://127.0.0.1:8000/', max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tezkor Menyu',
                'verbose_name_plural': 'Tezkor Menyular',
            },
        ),
    ]
