# Generated by Django 5.1.2 on 2025-01-28 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samtuit', '0024_quickmmenu'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listsmenu',
            options={'verbose_name': 'Menyular', 'verbose_name_plural': '2-Menyular '},
        ),
        migrations.AlterModelOptions(
            name='menu',
            options={'verbose_name': 'Menyu', 'verbose_name_plural': '1-Menyular'},
        ),
        migrations.AlterField(
            model_name='listsmenu',
            name='slug',
            field=models.SlugField(blank=True, help_text='Ota menu bolsa slug tanlangan 1-Menu saxifasidagi urlga joylashtiring', unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='listsmenu',
            name='url',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='url',
            field=models.CharField(blank=True, default='http://127.0.0.1:8000/', help_text="\n                http://127.0.0.1:8000/views/ \n                           `#news#announcements#meetings#gatherings#seminars#conversations#round/talks#`, \n                           `bitalik ma'lumot->#about/slug#`, \n                           `2-menu->#slug#`,\n                http://127.0.0.1:8000/ \n                           `rektor->#leader#`,\n                           `kafedralar->#kafedralar#`,\n                           `markazlar->#markazlar#`,\n                           `fakultetlar->#fakultetlar#`,\n                           `Aloqa -> #contact#,\n            ", max_length=200, null=True),
        ),
    ]
