# Generated by Django 5.1.2 on 2025-01-29 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samtuit', '0025_alter_listsmenu_options_alter_menu_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='url',
            field=models.CharField(blank=True, default='https://new.samtuit.uz/', help_text="\n                https://new.samtuit.uz/views/ \n                           `#news#announcements#meetings#gatherings#seminars#conversations#round/talks#`, \n                           `bitalik ma'lumot->#about/slug#`, \n                           `2-menu->#slug#`,\n                https://new.samtuit.uz/ \n                           `rektor->#leader#`,\n                           `kafedralar->#kafedralar#`,\n                           `markazlar->#markazlar#`,\n                           `fakultetlar->#fakultetlar#`,\n                           `Aloqa -> #contact#,\n            ", max_length=200, null=True),
        ),
    ]
