# Generated by Django 5.1.2 on 2025-02-15 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samtuit', '0026_alter_menu_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Ismi')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Eamil')),
                ('subject', models.CharField(blank=True, max_length=50, null=True, verbose_name='Mavzu')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Xabar')),
            ],
            options={
                'verbose_name': 'Aloqa',
                'verbose_name_plural': 'Aloqalar',
            },
        ),
    ]
