# Generated by Django 5.1.2 on 2025-02-21 04:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samtuit', '0027_contact'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lists',
            options={'verbose_name_plural': "Menuli ma'lumotlar"},
        ),
        migrations.AlterField(
            model_name='quickmmenu',
            name='url',
            field=models.CharField(blank=True, default='https://new.samtuit.uz/', max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_uz', models.CharField(help_text='Sarlavha maksimal 200 belgi', max_length=200, null=True, verbose_name='Sarlovhasi')),
                ('text_uz', models.CharField(help_text='Sarlavha matini maksimal 550 belgi', max_length=550, null=True, verbose_name='Sarlovha matini')),
                ('title_en', models.CharField(help_text='English sarlavha maksimal 200 belgi', max_length=200, null=True, verbose_name='English sarlovhasi')),
                ('text_en', models.CharField(help_text='English sarlavha matini maksimal 500 belgi', max_length=500, null=True, verbose_name='English sarlovha matini')),
                ('title_ru', models.CharField(help_text='Ruscha sarlavha maksimal 200 belgi', max_length=200, null=True, verbose_name='Ruscha arlovhasi')),
                ('text_ru', models.CharField(help_text='Ruscha sarlavha matini maksimal 550 belgi', max_length=550, null=True, verbose_name='Ruscha arlovha matini')),
                ('files', models.FileField(blank=True, null=True, upload_to='file/', verbose_name='Fayl')),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('listmenu', models.ForeignKey(blank=True, help_text='Menuyuda aks etadi', null=True, on_delete=django.db.models.deletion.SET_NULL, to='samtuit.listsmenu', verbose_name='Menusi')),
            ],
            options={
                'verbose_name_plural': "File menuli ma'lumotlar",
            },
        ),
    ]
