# Generated by Django 5.1.2 on 2025-02-21 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samtuit', '0028_alter_lists_options_alter_quickmmenu_url_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='text_en',
            field=models.CharField(blank=True, help_text='English sarlavha matini maksimal 500 belgi', max_length=500, null=True, verbose_name='English sarlovha matini'),
        ),
        migrations.AlterField(
            model_name='files',
            name='text_ru',
            field=models.CharField(blank=True, help_text='Ruscha sarlavha matini maksimal 550 belgi', max_length=550, null=True, verbose_name='Ruscha arlovha matini'),
        ),
        migrations.AlterField(
            model_name='files',
            name='text_uz',
            field=models.CharField(blank=True, help_text='Sarlavha matini maksimal 550 belgi', max_length=550, null=True, verbose_name='Sarlovha matini'),
        ),
        migrations.AlterField(
            model_name='files',
            name='title_en',
            field=models.CharField(blank=True, help_text='English sarlavha maksimal 200 belgi', max_length=200, null=True, verbose_name='English sarlovhasi'),
        ),
        migrations.AlterField(
            model_name='files',
            name='title_ru',
            field=models.CharField(blank=True, help_text='Ruscha sarlavha maksimal 200 belgi', max_length=200, null=True, verbose_name='Ruscha arlovhasi'),
        ),
        migrations.AlterField(
            model_name='files',
            name='title_uz',
            field=models.CharField(blank=True, help_text='Sarlavha maksimal 200 belgi', max_length=200, null=True, verbose_name='Sarlovhasi'),
        ),
    ]
