# Generated by Django 5.1.2 on 2025-02-22 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samtuit', '0029_alter_files_text_en_alter_files_text_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lists',
            name='is_file',
            field=models.BooleanField(default=False, help_text="Agar fayl chiqish bo'lsa belgilang", verbose_name='Text va fayl chiqish'),
        ),
        migrations.DeleteModel(
            name='Files',
        ),
    ]
