# Generated by Django 5.1.2 on 2025-01-07 14:06

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadership', '0002_leadership_position_en_leadership_position_ru_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, help_text='Rasm o‘lchami 370x250 piksel bo‘lishi kerak!', null=True, upload_to='kafedra/', verbose_name='Direktor rasmi')),
                ('titul_uz', models.CharField(blank=True, help_text="Kafedra nomi  O'zbekcha kiriting", max_length=200, null=True, verbose_name='Kafedra nomi')),
                ('titul_en', models.CharField(blank=True, help_text="Kafedra nomi  O'zbekcha kiriting", max_length=200, null=True, verbose_name='Kafedra nomi')),
                ('titul_ru', models.CharField(blank=True, help_text="Kafedra nomi  O'zbekcha kiriting", max_length=200, null=True, verbose_name='Kafedra nomi')),
                ('text_uz', models.CharField(blank=True, help_text='Sarlovha 500 belgi', max_length=500, null=True, verbose_name='Sarlovha matini:')),
                ('text_en', models.CharField(blank=True, help_text='Sarlovha 500 belgi', max_length=500, null=True, verbose_name='Sarlovha matini:')),
                ('text_ru', models.CharField(blank=True, help_text='Sarlovha 500 belgi', max_length=500, null=True, verbose_name='Sarlovha matini:')),
                ('full_name_uz', models.CharField(blank=True, help_text="Familiya Ism Otasini ism  O'zbekcha kiriting", max_length=200, null=True, verbose_name='Kafedra muduri F.I.O:')),
                ('full_name_en', models.CharField(blank=True, help_text='Familiya Ism Otasini ism  Englizcha kiriting', max_length=200, null=True, verbose_name='Kafedra muduri F.I.O:')),
                ('full_name_ru', models.CharField(blank=True, help_text='Familiya Ism Otasini ism  Ruscha kiriting', max_length=200, null=True, verbose_name='Kafedra muduri F.I.O:')),
                ('acceptance', models.CharField(blank=True, help_text='Chorshanba - Juma, 15:00 - 17:00', max_length=100, null=True, verbose_name='Qabul:')),
                ('phone', models.CharField(blank=True, help_text='+998901234567', max_length=20, null=True, verbose_name='Telefon:')),
                ('email', models.CharField(blank=True, help_text='z.karshiyev@samtuit.uz, zaynidin85@gmail.com', max_length=200, null=True, verbose_name='Email:')),
                ('content_uz', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Biografiya Uzb')),
                ('content_en', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Biografiya Eng')),
                ('content_ru', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Biografiya Rus')),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Kafedra',
            },
        ),
    ]
