# Generated by Django 5.1.2 on 2025-01-08 04:09

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadership', '0003_departments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departments',
            options={'verbose_name_plural': 'Kafedralar'},
        ),
        migrations.RemoveField(
            model_name='departments',
            name='acceptance',
        ),
        migrations.RemoveField(
            model_name='departments',
            name='email',
        ),
        migrations.RemoveField(
            model_name='departments',
            name='full_name_en',
        ),
        migrations.RemoveField(
            model_name='departments',
            name='full_name_ru',
        ),
        migrations.RemoveField(
            model_name='departments',
            name='full_name_uz',
        ),
        migrations.RemoveField(
            model_name='departments',
            name='phone',
        ),
        migrations.AlterField(
            model_name='departments',
            name='content_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name="Kafedra ma'limot Eng"),
        ),
        migrations.AlterField(
            model_name='departments',
            name='content_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name="Kafedra ma'limot Rus"),
        ),
        migrations.AlterField(
            model_name='departments',
            name='content_uz',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name="Kafedra ma'limot Uzb"),
        ),
        migrations.AlterField(
            model_name='departments',
            name='image',
            field=models.ImageField(blank=True, help_text='Rasm o‘lchami 370x250 piksel bo‘lishi kerak!', null=True, upload_to='kafedra/', verbose_name='Kafedra rasmi'),
        ),
    ]
