# Generated by Django 5.1.2 on 2025-01-08 06:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadership', '0007_alter_departments_titul_en_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, help_text='Rasm o‘lchami 370x250 piksel bo‘lishi kerak!', null=True, upload_to='kafedra/', verbose_name='Kafedra rasmi')),
                ('title_uz', models.CharField(blank=True, help_text="Kafedra nomi O'zbekcha kiriting", max_length=200, null=True, verbose_name='Kafedra nomi UZB')),
                ('title_en', models.CharField(blank=True, help_text='Kafedra nomi Englizcha kiriting', max_length=200, null=True, verbose_name='Kafedra nomi ENG')),
                ('title_ru', models.CharField(blank=True, help_text='Kafedra nomi Ruscha kiriting', max_length=200, null=True, verbose_name='Kafedra nomi RUS')),
                ('text_uz', models.TextField(blank=True, help_text='Sarlovha', null=True, verbose_name='Sarlovha matini:')),
                ('text_en', models.TextField(blank=True, help_text='Sarlovha', null=True, verbose_name='Sarlovha matini:')),
                ('text_ru', models.TextField(blank=True, help_text='Sarlovha', null=True, verbose_name='Sarlovha matini:')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Kafedralar',
            },
        ),
        migrations.AddField(
            model_name='departments',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='leadership.faculty', verbose_name='Fakultet:'),
        ),
    ]
