# Generated by Django 5.1.2 on 2025-01-08 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadership', '0009_facultydean'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faculty',
            options={'verbose_name_plural': 'Fakultetlar'},
        ),
        migrations.AlterModelOptions(
            name='facultydean',
            options={'verbose_name_plural': 'Dekanat'},
        ),
        migrations.AddField(
            model_name='faculty',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
