# Generated by Django 5.1.2 on 2025-01-08 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadership', '0010_alter_faculty_options_alter_facultydean_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departments',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kafedra', to='leadership.faculty', verbose_name='Fakultet:'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='image',
            field=models.ImageField(blank=True, help_text='Rasm o‘lchami 740x500 piksel bo‘lishi kerak!', null=True, upload_to='kafedra/', verbose_name='Kafedra rasmi'),
        ),
        migrations.AlterField(
            model_name='facultydean',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dekanlar', to='leadership.faculty', verbose_name='Fakultet:'),
        ),
        migrations.AlterField(
            model_name='facultydean',
            name='image',
            field=models.ImageField(blank=True, help_text='Rasm o‘lchami 270x201 piksel bo‘lishi kerak!', null=True, upload_to='rektorat/', verbose_name='Dekan rasmi'),
        ),
    ]
