# Generated by Django 5.1.2 on 2025-06-30 10:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserHemis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hemis_id', models.CharField(max_length=100, unique=True, verbose_name='Hemis ID')),
                ('phone', models.CharField(max_length=13, verbose_name='Telefon raqami')),
                ('short_name', models.CharField(max_length=100, verbose_name='Qisqartma ismi')),
                ('userStatus', models.CharField(max_length=100, verbose_name='Foydalanuvchi holati')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Foydalanuvchilar',
                'verbose_name_plural': "Foydalanuvchilar ro'yxati",
            },
        ),
    ]
