# Generated by Django 5.1.2 on 2025-07-09 10:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GrantApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty', models.CharField(blank=True, max_length=100, null=True, verbose_name='Fakultet')),
                ('group', models.CharField(blank=True, max_length=100, null=True, verbose_name='Guruh')),
                ('gpa_ball', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='GPA balli')),
                ('application_date', models.DateTimeField(auto_now_add=True, verbose_name='Ariza yuborilgan sana')),
                ('file', models.FileField(upload_to='grant_applications/', verbose_name='Ariza fayli')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('approved', 'Tasdiqlangan'), ('rejected', 'Rad etilgan')], default='pending', max_length=50, verbose_name='Ariza holati')),
                ('new_phone', models.CharField(max_length=20, verbose_name='Yangi telefon raqam')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='Izohlar')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Grant arizasi',
                'verbose_name_plural': 'Grant arizalari',
            },
        ),
        migrations.CreateModel(
            name='UserHemis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hemis_id', models.CharField(max_length=100, unique=True, verbose_name='Hemis ID')),
                ('phone', models.CharField(max_length=13, verbose_name='Telefon raqami')),
                ('short_name', models.CharField(max_length=100, verbose_name='Qisqartma ismi')),
                ('userStatus', models.CharField(max_length=100, verbose_name='Foydalanuvchi holati')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Foydalanuvchilar',
                'verbose_name_plural': "Foydalanuvchilar ro'yxati",
            },
        ),
    ]
