# Generated by Django 5.1.2 on 2025-06-30 12:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interaktiv', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GrantApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_date', models.DateTimeField(auto_now_add=True, verbose_name='Ariza yuborilgan sana')),
                ('file', models.FileField(upload_to='grant_applications/', verbose_name='Ariza fayli')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('approved', 'Tasdiqlangan'), ('rejected', 'Rad etilgan')], default='pending', max_length=50, verbose_name='Ariza holati')),
                ('new_phone', models.CharField(max_length=20, verbose_name='Yangi telefon raqam')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='Izohlar')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Grant arizasi',
                'verbose_name_plural': 'Grant arizalari',
            },
        ),
    ]
