# Generated by Django 5.1.2 on 2025-07-09 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interaktiv', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grantapplication',
            name='social_activism_field',
            field=models.FileField(blank=True, null=True, upload_to='social_activism/', verbose_name='Ijtimoiy faoliyat fayli'),
        ),
    ]
