# Generated by Django 5.1.2 on 2025-07-09 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interaktiv', '0002_grantapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='grantapplication',
            name='faculty',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Fakultet'),
        ),
        migrations.AddField(
            model_name='grantapplication',
            name='gpa_ball',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='GPA balli'),
        ),
        migrations.AddField(
            model_name='grantapplication',
            name='group',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Guruh'),
        ),
        migrations.AddField(
            model_name='grantapplication',
            name='social_activism_flied',
            field=models.FileField(blank=True, null=True, upload_to='social_activism/', verbose_name='Ijtimoiy faoliyat fayli'),
        ),
    ]
