# Generated by Django 5.1.2 on 2025-07-22 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interaktiv', '0002_grantapplication_social_activism_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForeignStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ism')),
                ('last_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Familiya')),
                ('phone', models.CharField(blank=True, max_length=13, null=True, verbose_name='Telefon raqami')),
                ('country', models.CharField(blank=True, max_length=100, null=True, verbose_name='Mamlakat')),
                ('passport_file', models.FileField(blank=True, null=True, upload_to='passports/', verbose_name='Pasport fayli')),
                ('diploma_file', models.FileField(blank=True, null=True, upload_to='diplomas/', verbose_name='Diplom fayli')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
            ],
            options={
                'verbose_name': 'Chet el talabalari',
                'verbose_name_plural': "Chet el talabalari ro'yxati",
            },
        ),
    ]
