# Generated by Django 5.1.2 on 2025-08-01 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interaktiv', '0003_foreignstudent'),
    ]

    operations = [
        migrations.AddField(
            model_name='grantapplication',
            name='ball',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Ball'),
        ),
        migrations.AddField(
            model_name='grantapplication',
            name='is_visible_to_user',
            field=models.BooleanField(default=False, verbose_name='Baholar foydalanuvchiga ko‘rinsinmi'),
        ),
        migrations.AddField(
            model_name='grantapplication',
            name='total_ball',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Jami ball'),
        ),
    ]
